services:
  # 游냀 Producer Python
  producer1_s2:
    build:
      context: ./producer
    container_name: producer1_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2   # Broker en el nodo 2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游릭 Producer Node.js
  producer2_s2:
    build:
      context: ./producer2
    container_name: producer2_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游리 Producer Go
  producer3_s2:
    build:
      context: ./producer3
    container_name: producer3_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游댯 Producer Go (segundo)
  producer4_s2:
    build:
      context: ./producer4
    container_name: producer4_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游냀 Consumer Python
  consumer1_s2:
    build:
      context: ./consumer
    container_name: consumer1_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游릭 Consumer Node.js
  consumer2_s2:
    build:
      context: ./consumer2
    container_name: consumer2_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游리 Consumer Go
  consumer3_s2:
    build:
      context: ./consumer3
    container_name: consumer3_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游댯 Consumer Java
  consumer4_s2:
    build:
      context: ./consumer4
    container_name: consumer4_s2
    environment:
      - RABBIT_HOST=rabbitmq1_s2
      - RABBIT_USER=user
      - RABBIT_PASS=password
    depends_on:
      - placeholder_s2
    networks:
      - rabbitnet

  # 游댲 Contenedor temporal (para dependencias internas)
  placeholder_s2:
    image: alpine
    command: tail -f /dev/null
    container_name: placeholder_s2
    networks:
      - rabbitnet

# 游댕 Red compartida con el Nodo 2
networks:
  rabbitnet:
    external: true
